### ISSUE TITLE
mining drill not craftable

### ISSUE THREAD

**Issue by programmerjake** [Der1248/Regnum#11]
the items named `technic:drill_mkS1`..`technic:drill_mkS150` were removed in [cc0f4519a0](https://github.com/Der1248/Regnum/commit/cc0f4519a039bef3ce284af2699b91654f1a9c5e#diff-320c2f5e9db9fa464f23440db3d74afd9ad4a5582356c82d20c92229953c86f1), but the crafting recipes still name them.

**Comment by Der1248** [comment]
should be fixed with version 3.6.5
