### ISSUE TITLE
can't craft gun level 46 due to typo

### ISSUE THREAD

**Issue by programmerjake** [Der1248/Regnum#4]
https://github.com/Der1248/Regnum/blob/a16d4bc8ccdcd42e8e29dd427d3b810dd0f53f71/mods/tutorial/init.lua#L4487

Shouldn't that be:
```lua
{'tutorial:zauberstab9', 'tutorial:cloudgun_mega25', 'tutorial:swored_zauber9'},
```

**Comment by WSDguy2014** [comment]
I reproduced a problem in Regnum version 3.3.7 and its confirmed.
![image](https://user-images.githubusercontent.com/13905392/69483506-ce43f280-0e30-11ea-873e-7f711c263c7c.png)
Please fix this, it should be easy for the next update.

**Comment by Der1248** [comment]
I will fix that

**Comment by Der1248** [comment]
should be fixed
