### ISSUE TITLE
(3.3.7) Helicopter sometimes being glitchy.

### ISSUE THREAD

**Issue by WSDguy2014** [Der1248/Regnum#6]
Game version: 3.3.7

The annoying glitch caused by trying to ride a helicopter far from the x, y and z coordinates 0.
Placing and trying to ride helicopter that is far from the x0, y0, z0, might cause teleportation and a chance that player will loose a helicopter.

**Comment by Der1248** [comment]
That is interesting. I will try to fix that for the next version.

**Comment by Der1248** [comment]
I use a new version of the helicopter mod. Should be fixed now.
