### ISSUE TITLE
(3.3.7) It's possible to kill player pet mobs.

### ISSUE THREAD

**Issue by WSDguy2014** [Der1248/Regnum#7]
@Der1248, i had to pause my playthrough after i got 2 pet mobs from DNA Crafting and waiting for the new update version to fix this problem as soon as possible. Why?

How to reproduce?

Make a structure in the 3x3 like this:
![image](https://user-images.githubusercontent.com/13905392/70062144-27104980-15ee-11ea-988e-0c7db23eceb0.png)
This is where you kill your own pet mobs. If you can't do this using this structure, do it something different.

Have your Regnum Gun with the secondary mode to create thunder blocks.

Spawn any your mob pet at this 3x3 building structure and shoot it to create thunder blocks that might have maximum level. Simply shooting your mob pet just gives knockback and without any damage, until thunder blocks can actually kill your mob pets.
Once you killed your own mob pet(s) using maximum level of thunder blocks, you cannot get a new mob pet using DNA Crafting, as it can craft each every 6 mob types of spawn eggs once, that's it. It's not possible to renew mob spawn eggs using DNA Crafting.

To fix a problem: If any one of spawned player pet mobs dies, revert one of the pet mob DNA from "complete" to 0%, renew to craft a new same pet mob.

**Comment by WSDguy2014** [comment]
What if not an mob pet entity itself, how about spawn egg items of your pet mobs?

Before using it to spawn into a pet mob entity, dropping an item spawn egg of any your pet mob and let despawn, how can you craft new one if it's first one despawned?

**Comment by Der1248** [comment]
I now tested this and it is possible, you are right. I will try to fix this in the next version

**Comment by Der1248** [comment]
should be fixed now
