### ISSUE TITLE
(3.3.7) Player pet mobs attacking each other.

### ISSUE THREAD

**Issue by WSDguy2014** [Der1248/Regnum#8]
As this name of annoying glitch suggests, player pet mobs attacking each other if it's not the same player pet mob entity (for example: own cat is attacking own dragon each other).
This is annoying and should not do that. @Der1248, please fix this annoying problem.

**Comment by Der1248** [comment]
Will be fixed in Regnum 3.4.0

**Comment by Der1248** [comment]
should be fixed now
